<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-26T14:48:03 IST" name="Failed suite [Suite]" finished-at="2024-09-26T14:49:45 IST" duration-ms="102905">
    <groups>
    </groups>
    <test started-at="2024-09-26T14:48:03 IST" name="Test(failed)" finished-at="2024-09-26T14:49:45 IST" duration-ms="102905">
      <class name="testCases.TC015_CreatePublicStrategy">
        <test-method is-config="true" signature="setUpClass(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC015_CreatePublicStrategy@4e858e0a]" started-at="2024-09-26T14:48:03 IST" name="setUpClass" finished-at="2024-09-26T14:48:03 IST" duration-ms="65" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:testCases.TC015_CreatePublicStrategy@4e858e0a]" started-at="2024-09-26T14:48:03 IST" name="setUp" finished-at="2024-09-26T14:48:12 IST" duration-ms="8630" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="create_Public_strategy()[pri:0, instance:testCases.TC015_CreatePublicStrategy@4e858e0a]" started-at="2024-09-26T14:48:12 IST" name="create_Public_strategy" finished-at="2024-09-26T14:48:34 IST" duration-ms="22523" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to an exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to an exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC015_CreatePublicStrategy.create_Public_strategy(TC015_CreatePublicStrategy.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_Public_strategy -->
        <test-method is-config="true" signature="tearDownMethod()[pri:0, instance:testCases.TC015_CreatePublicStrategy@4e858e0a]" started-at="2024-09-26T14:48:35 IST" name="tearDownMethod" finished-at="2024-09-26T14:48:35 IST" duration-ms="434" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:testCases.TC015_CreatePublicStrategy@4e858e0a]" started-at="2024-09-26T14:48:35 IST" name="tearDownClass" finished-at="2024-09-26T14:48:35 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- testCases.TC015_CreatePublicStrategy -->
      <class name="testCases.TC004_CreateMT4AccountTest">
        <test-method is-config="true" signature="setUpClass(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC004_CreateMT4AccountTest@696f0212]" started-at="2024-09-26T14:49:11 IST" name="setUpClass" finished-at="2024-09-26T14:49:11 IST" duration-ms="6" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:testCases.TC004_CreateMT4AccountTest@696f0212]" started-at="2024-09-26T14:49:11 IST" name="setUp" finished-at="2024-09-26T14:49:20 IST" duration-ms="8622" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="createMT4_Account()[pri:0, instance:testCases.TC004_CreateMT4AccountTest@696f0212]" started-at="2024-09-26T14:49:20 IST" name="createMT4_Account" finished-at="2024-09-26T14:49:45 IST" duration-ms="24926" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createMT4_Account -->
        <test-method is-config="true" signature="tearDownMethod()[pri:0, instance:testCases.TC004_CreateMT4AccountTest@696f0212]" started-at="2024-09-26T14:49:45 IST" name="tearDownMethod" finished-at="2024-09-26T14:49:45 IST" duration-ms="752" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:testCases.TC004_CreateMT4AccountTest@696f0212]" started-at="2024-09-26T14:49:45 IST" name="tearDownClass" finished-at="2024-09-26T14:49:45 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- testCases.TC004_CreateMT4AccountTest -->
      <class name="testCases.TC005_DepositFundsUSDTest">
        <test-method is-config="true" signature="setUpClass(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC005_DepositFundsUSDTest@b7838a9]" started-at="2024-09-26T14:48:35 IST" name="setUpClass" finished-at="2024-09-26T14:48:35 IST" duration-ms="8" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:testCases.TC005_DepositFundsUSDTest@b7838a9]" started-at="2024-09-26T14:48:35 IST" name="setUp" finished-at="2024-09-26T14:48:43 IST" duration-ms="7592" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="approvedepositFundsUSD()[pri:2, instance:testCases.TC005_DepositFundsUSDTest@b7838a9]" started-at="2024-09-26T14:48:43 IST" name="approvedepositFundsUSD" finished-at="2024-09-26T14:49:10 IST" duration-ms="27774" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to an exception: no such element: Unable to locate element: {"method":"xpath","selector":"//i[@data-dismiss='modal']"}
  (Session info: chrome=129.0.6668.70)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.23.1', revision: '656257d8e9'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.4'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [6c30c655e34125318eaf10c075147020, findElement {using=xpath, value=//i[@data-dismiss='modal']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.70, chrome: {chromedriverVersion: 129.0.6668.70 (df87d5cf12b1..., userDataDir: C:\Users\ABDULS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:56740}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:56740/devtoo..., se:cdpVersion: 129.0.6668.70, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 6c30c655e34125318eaf10c075147020]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to an exception: no such element: Unable to locate element: {"method":"xpath","selector":"//i[@data-dismiss='modal']"}
  (Session info: chrome=129.0.6668.70)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.23.1', revision: '656257d8e9'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.4'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [6c30c655e34125318eaf10c075147020, findElement {using=xpath, value=//i[@data-dismiss='modal']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.70, chrome: {chromedriverVersion: 129.0.6668.70 (df87d5cf12b1..., userDataDir: C:\Users\ABDULS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:56740}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:56740/devtoo..., se:cdpVersion: 129.0.6668.70, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 6c30c655e34125318eaf10c075147020
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC005_DepositFundsUSDTest.approvedepositFundsUSD(TC005_DepositFundsUSDTest.java:77)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- approvedepositFundsUSD -->
        <test-method is-config="true" signature="tearDownMethod()[pri:0, instance:testCases.TC005_DepositFundsUSDTest@b7838a9]" started-at="2024-09-26T14:49:11 IST" name="tearDownMethod" finished-at="2024-09-26T14:49:11 IST" duration-ms="438" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownMethod -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:testCases.TC005_DepositFundsUSDTest@b7838a9]" started-at="2024-09-26T14:49:11 IST" name="tearDownClass" finished-at="2024-09-26T14:49:11 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- testCases.TC005_DepositFundsUSDTest -->
    </test> <!-- Test(failed) -->
  </suite> <!-- Failed suite [Suite] -->
</testng-results>
